### PR TITLE
fix: add jwt authentication and needed configs

### PR DESCRIPTION
**Pull request by DarthUdp**
this is a pretty big change so I'm opening this pr early on so we can discuss, as the front-end will need an update as well

### CODE REVIEW

**Comment by l3alr0g** [comment]
Thank you, I'll take a look at this whenever possible.

**Comment by DarthUdp** [comment]
I have a host of improvements to commit later today, in regards to the citadel class, and I would like to suggest transitioning this project to typescript as it helps quite a lot with maintainability.

**Comment by l3alr0g** [comment]
> I would like to suggest transitioning this project to typescript as it helps quite a lot with maintainability.
Good thing you mention that because I had planned to do it while updating the API routes to be lighter and more efficient.
I'll mark this PR as draft if you aren't done yet 😁

**Comment by DarthUdp** [comment]
So I think this change is important enough and is in a merge-able state now such that you may merge it, the main issue is the front-end needs changes in how it talks to pulsar.

**Comment by DarthUdp** [comment]
Hey @l3alr0g can you update the tests? I can provide some guidance, I think this is the only blocker to merging together with implementing this authentication scheme on the client (which is kinda beyond me since I focus mostly on back-end related stuff).

Here are some curls to help
This one is how to call the new /authenticate/jwt endpoint
```sh
curl --request POST \
  --url http://localhost:5000/authenticate/jwt \
  --header 'Content-Type: application/json' \
  --data '{
	"username": "exampleUser",
	"password": "30aac1b9904b8226f1d86f6c1cf871adb9efec9ca69d735c59a43c66ce53b958"
}'
```
Reponse:
```json
{
  "bearer": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjZWEyYzk2MC1hMTM0LTQ3NTgtYjA3Ni1mYTU3OGRlZWEzYWMiLCJpc3MiOiJiMGIyMzgwMzI3OWY4MmEyOGIwZGI0MTE4ZjY4OGRkY2VlMzA4ZTBjYjY4OWY4OTJmMmE0N2MwMDc0YzM2ZjI3IiwiZXhwIjoxNjMxODU4MDEzLCJpYXQiOjE2MzE4NTQ0MTN9.btGkJagfdROkMqynHIBpIr_6UJJrpkMUCFj8EpvSaEc"
}
```
You want to save the bearer somewhere and later on send it like so in the headers with every request
```sh
curl --request GET \
  --url http://localhost:5000/status-compact \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjZWEyYzk2MC1hMTM0LTQ3NTgtYjA3Ni1mYTU3OGRlZWEzYWMiLCJpc3MiOiJiMGIyMzgwMzI3OWY4MmEyOGIwZGI0MTE4ZjY4OGRkY2VlMzA4ZTBjYjY4OWY4OTJmMmE0N2MwMDc0YzM2ZjI3IiwiZXhwIjoxNjMxODU4MDEzLCJpYXQiOjE2MzE4NTQ0MTN9.btGkJagfdROkMqynHIBpIr_6UJJrpkMUCFj8EpvSaEc'
```
Returns are kept the same save for status codes that I changed from all 401 to proper codes

**Comment by l3alr0g** [comment]
Got it, I'm updating the tests whenever I can (I'm a bit busy with work rn). Also, we're gonna need to merge this into a secondary branch, such as security/rewamp, which I just created. 
Can you rebase the pr ? I'll merge it when the CI returns no errors.

**Comment by l3alr0g** [comment]
I can't get your code to run, I keep getting this error : 
```
Error: Cannot find module 'node:crypto'
```
What version of node are you running ?
Also, there's already a vs code workspace, so the .vscode and .idea folders should be added to the gitignore.

**Comment by DarthUdp** [comment]
image
This suggests the crypto module is in node for a while now, maybe try to change the `node:crypto` for `crypto`, I'm at work so I can't change it now.

**Comment by l3alr0g** [comment]
I have taken a quick look at your code, and I just thought username/password authentication just doesn't make sense at this point, because there is no actual database to store all of these users. It would be much better to stick to the good old key-based auth, using your upgraded, more secure version.

Also, from the curls I have run, one problem seems to have emerged : the bearer seems to change everytime you make a request, which forces you to re authenticate every time you want to retrieve data. Is it just me using the api wrong ?

Can you please take a look at this whenever possible ?

**Comment by DarthUdp** [comment]
> Also, from the curls I have run, one problem seems to have emerged : the bearer seems to change everytime you make a request, which forces you to re authenticate every time you want to retrieve data. Is it just me using the api wrong ?
> 
> Can you please take a look at this whenever possible ?

A bearer is valid for some amount of time so you should call the authentication endpoint once store the bearer and use it for subsequent requests you can then verify it's expiration date or until it returns 403 to call the authentication endpoint once more.

https://jwt.io is a great resource on these tokens

I will write a more detailed version once I'm done with work

**Comment by DarthUdp** [comment]
the idea is that you are not transmitting your secret every request and a leaked token then has a limited impact restricted to it's expiration.

**Comment by DarthUdp** [comment]
> I have taken a quick look at your code, and I just thought username/password authentication just doesn't make sense at this point, because there is no actual database to store all of these users. It would be much better to stick to the good old key-based auth, using your upgraded, more secure version.

A pair of secrets is more secure than a single secret (in the brute-forcing sense), but we can use just one as well, I'd rename them to clientId and clientSecret.

**Comment by l3alr0g** [comment]
Yes, I know, but with a long enough secret I think we should be totally fine.

**Comment by DarthUdp** [comment]
I didn't manage to write this more detailed description yesterday, so here it goes.

This is the way to use the new security system:
* The client makes a request to the /authentication/jwt endpoint sending in json a single key, `sharedSecret`;
* Upon validation of the `sharedSecret` the server will respond with either a json with a single key `bearer` containing the jwt token to use in subsequent requests or a 403 code indicating a invalid `sharedSecret` has been supplied, the client must halt attempts and prompt for the user to check the provided `sharedSecret`;
* The client upon receiving a token from the server saves it (in electron local storage is the preferred location), and send it in the Authorization header in every request prepended of Bearer (it WILL be rejected otherwise);
* The server will receive the token verify it's signature and check the expiration, if the signature is invalid or the current time is greater than the expiration time, the request will be rejected with a 403 code if accepted data will be returned as normal;
* Upon a 403 in the previous step the client should attempt the first step again to acquire a new token;

it's a fair deal more complex than the previous one but way more secure.

**Comment by l3alr0g** [comment]
Thank you, that's what I had figured out, it's worth noticing that for consistency reasons, I have renamed the `secretKey` field to `auth` in BearerAuth.js
I am working right now on making all of the necessary client-side updates.

**Comment by DarthUdp** [comment]
To me this looks good for merging in the separate branch.

**Pull request merged**
