### PR TITLE
Containerize using Docker

### PR DESCRIPTION
**Pull request by BrenekH**
This PR adds a basic Dockerfile to containerize Slashboard-pulsar.

One important thing to note is that the key is not generated automatically using this setup, it must be entered as an environment variable (`PULSAR_AUTH_KEY` currently) at container startup.

I am happy to make any changes necessary to make this work for the project.

### CODE REVIEW

**Review by BSoDium — APPROVED** [review]

**Comment by l3alr0g** [comment]
I have improved a couple of things :
- the key is now generated when the container is launched for the first time, and will be kept until deletion
- the docker image is automatically deployed to [Docker Hub](https://hub.docker.com/repository/docker/l3alr0g/slashboard-pulsar/general) on push for the main branch

However, a big issue remains : once run in the container instance, I have no idea how to allow node to access hardware data from the actual machine and not the container instance.
Any ideas ?

**Comment by BrenekH** [comment]
All of the CI/CD stuff looks good, but the changes to `docker_init.sh` should be reversed in favor of a different solution.

The reason it was originally setup to be entirely user defined was because `key.txt` resets to the default value every time the container starts. This is due to how containers work and is not a problem specific to this setup. A potential solution that ensures that the key is still generated by Pulsar is to allow users to generate a key using the docker container, which they then can put in the environment variable by themselves. An example of the command to do this from the user's side would be `docker run slashboard-pulsar genkey`, which would then output the key for the user to copy and paste. To implement this, `docker_init.sh` would check for the `genkey` argument, and if it was present, output a new key to STDOUT and exit.

As for the hardware data issue, my Linux machine reports everything just fine. What's your testing environment like?

**Comment by l3alr0g** [comment]
Actually, this would work if instead of running `docker run` each time we fire up Pulsar, we'd use `docker start` to reuse the previously created container. I just feel like this is an easier way of doing it, but if you think this is better, let's stick to it.

When it comes to the wrong hardware readings, I have tested this on linux and windows, and the results are the same : the hostname shows up as a meaningless alphanumeric string (the id of the container probably) and the disks and network interfaces are all messed up, because the node js app is retrieving hardware data from the container, not the host machine.

**Comment by BrenekH** [comment]
> I just feel like this is an easier and more logical way of doing it

Yeah I think #18 is the real answer to this which is unfortunate, because it'll probably be a while until that is ready. Also, `docker start` isn't going to keep `key.txt` around either, the image is read every time. The only way to persist files across starts is with volumes or bind mounts. I'm going to implement the genkey system since it's a nice compromise and will only be around for a little while.

I was mostly looking at CPU usage for my "tests", but you are correct that the info for the network and disks is container specific. I'm not too sure what the fix is, but I'll start looking into it.

**Comment by l3alr0g** [comment]
I just tested it on two computers

**Comment by l3alr0g** [comment]
Sorry, that's a missclick

**Comment by l3alr0g** [comment]
> Also, docker start isn't going to keep key.txt around either, the image is read every time.

I just tested that on two separate devices running windows and linux, and both seem to keep the content of the key.txt file tough. I suggest that you try it yourself : 
- run the image, check if the client can retrieve the data
- stop the container
- start it again, the client clearly still works, which implies that the key hasn't changed

**Comment by BrenekH** [comment]
Okay, you are correct. Using `docker start` retains the key after stopping the container. However, I still don't believe that trusting the users to run Pulsar one way, which is less common, is a good fix. Plus, `docker-compose down` does remove the containers, thus erasing the key, so anyone who uses that, will be out of luck.

On another note, I have a solution to the hostname/network adapters/disks problem. The fix is to add some options on container creation.
 * `--network host` fixes the network adapters and hostname by binding the container to the host's network instead of the docker virtual one. There is a small downside of port mappings being ignored, but it's not like the port can be changed when run natively anyway.
 * `--volume /dev/sda:/dev/sda` mounts the `/dev/sda` device to the container so that it can see it. This can be repeated by the user as many times as they like so that any disks they want to monitor are mounted. I'm not sure how well this works on Windows, but I did find a [Medium post](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c) talking about setting up traditional bind mounts which may or may not allow for the kind of inspection Pulsar needs.

**Comment by l3alr0g** [comment]
Awesome work! I'm fixing this, updating the readme and this PR should be good to go 😁

**Comment by l3alr0g** [comment]
I am starting to doubt of the feasibility of a dockerized performance monitor, there are just too many problems that come with it. Temp readings, live disk display and OS type are completely container-specific, which greatly limit the dashboard's capabilities, if we can't find a way to somehow easily communicate with the machine running docker, it might be better to just drop the idea.

**Comment by BrenekH** [comment]
I don't necessarily have a preference either way since it's not my project, although it would be a shame if the time already put in went to waste :man_shrugging:.

I do think that a dockerized machine monitor is possible as long as the user is willing to spend the time to set it up. Once everything is mounted, it'll probably just work, but getting to that point would be a pain depending on the system and the competence of the user.


@DarthUdp I know that you were interested in a docker version. Do you think it's worth it to go forward or should the docker effort be dropped?

**Comment by DarthUdp** [comment]
I was thinking about this Earlier I have two suggestions, move pulsar to a compiled language or find a way to package the current code in a self contained binary if electron exists I'm pretty sure a similar thing should exist for pure node.

**Comment by BrenekH** [comment]
Well, I'm all for moving to Go (shameless fanboying), but [Nexe](https://github.com/nexe/nexe) doesn't look like a bad option for a single executable while keeping the project JavaScript based.

Another solution to the node setup problem is to use distribution packaging methods (`.deb`, `.rpm`, etc) plus a Windows installer for that crowd.

**Comment by l3alr0g** [comment]
I'll try some of these solutions out, but for now, I need to do some further research concerning communication between the machine and its hosted containers. @BrenekH can you open a new PR so we can merge this branch into `docker` ?

**Comment by BrenekH** [comment]
The base for this has been changed to `docker` so it can be merged whenever you're ready.

**Comment by l3alr0g** [comment]
That's even better, I didn't know you could do that to be honest.

**Comment by DarthUdp** [comment]
> Well, I'm all for moving to Go (shameless fanboying), but [Nexe](https://github.com/nexe/nexe) doesn't look like a bad option for a single executable while keeping the project JavaScript based.
> 
> Another solution to the node setup problem is to use distribution packaging methods (`.deb`, `.rpm`, etc) plus a Windows installer for that crowd.

I like the idea of nexe, it seems nice, however distro packaging would present it's own host of possible issues.

**Pull request merged**
